# ©AngelaMos | 2026
# .rubocop.yml

plugins:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rake

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4
  Exclude:
    - "vendor/**/*"
    - "docs/**/*"
    - "tmp/**/*"

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes

Style/FormatStringToken:
  Enabled: false

Style/RedundantFormat:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Security/MarshalLoad:
  Enabled: false

Minitest/EmptyLineBeforeAssertionMethods:
  Enabled: false

Minitest/MultipleAssertions:
  Max: 12

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 50

Metrics/CyclomaticComplexity:
  Max: 30

Metrics/PerceivedComplexity:
  Max: 30

Metrics/ParameterLists:
  CountKeywordArgs: false

Metrics/ClassLength:
  Max: 250
  Exclude:
    - "test/**/*"

Metrics/ModuleLength:
  Exclude:
    - "test/**/*"

Layout/LineLength:
  Max: 120

Lint/RescueException:
  Exclude:
    - "test/**/*"

Lint/EmptyClass:
  Exclude:
    - "test/**/*"

Lint/UselessMethodDefinition:
  Exclude:
    - "test/**/*"

Style/MutableConstant:
  Exclude:
    - "test/**/*"

Minitest/AssertTruthy:
  Enabled: false

Minitest/RefuteFalse:
  Enabled: false

Style/EvalWithLocation:
  Exclude:
    - "test/**/*"

Style/OptionalBooleanParameter:
  Exclude:
    - "test/**/*"
