# ©AngelaMos | 2026
# Gemfile
# frozen_string_literal: true

source "https://rubygems.org"

gemspec

gem "minitest", "~> 6.0"
gem "rake", "~> 13.3"
gem "rubocop", "~> 1.88"
gem "rubocop-minitest", "~> 0.38"
gem "rubocop-performance", "~> 1.26"
gem "rubocop-rake", "~> 0.7"
